# Generated by Django 3.2.6 on 2021-08-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=15)),
                ('company_address', models.CharField(max_length=30)),
                ('company_telephone', models.CharField(max_length=15)),
                ('company_nit', models.CharField(max_length=10)),
            ],
        ),
    ]
